version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: job_scraper_db
    environment:
      POSTGRES_DB: job_scraper
      POSTGRES_USER: scraper_user
      POSTGRES_PASSWORD: scraper_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scraper_user -d job_scraper"]
      interval: 30s
      timeout: 10s
      retries: 3

  job-scraper:
    build: .
    container_name: job_scraper_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=job_scraper
      - DB_USER=scraper_user
      - DB_PASSWORD=scraper_password
    volumes:
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
    restart: unless-stopped

volumes:
  postgres_data:
